-- Draftable entries for our format (338 rows), generated from format.csv.
-- ids are national dex row ids from that sheet; forms are separate entries.
-- Prices are NOT here: costs are per-season and land via the CSV import.

INSERT INTO pokemon (id, slug, display_name) VALUES
  (3, 'venusaur', 'Venusaur'),
  (4, 'venusaur-mega', 'Venusaur (Mega)'),
  (7, 'charizard', 'Charizard'),
  (8, 'charizard-mega-x', 'Charizard (Mega-X)'),
  (9, 'charizard-mega-y', 'Charizard (Mega-Y)'),
  (12, 'blastoise', 'Blastoise'),
  (13, 'blastoise-mega', 'Blastoise (Mega)'),
  (19, 'beedrill', 'Beedrill'),
  (20, 'beedrill-mega', 'Beedrill (Mega)'),
  (23, 'pidgeot', 'Pidgeot'),
  (24, 'pidgeot-mega', 'Pidgeot (Mega)'),
  (32, 'arbok', 'Arbok'),
  (33, 'pikachu', 'Pikachu'),
  (35, 'raichu', 'Raichu'),
  (36, 'raichu-alola', 'Raichu (Alola)'),
  (1217, 'raichu-mega-x', 'Raichu (Mega-X)'),
  (1218, 'raichu-mega-y', 'Raichu (Mega-Y)'),
  (48, 'clefable', 'Clefable'),
  (1219, 'clefable-mega', 'Clefable (Mega)'),
  (51, 'ninetales', 'Ninetales'),
  (52, 'ninetales-alola', 'Ninetales (Alola)'),
  (54, 'wigglytuff', 'Wigglytuff'),
  (59, 'vileplume', 'Vileplume'),
  (71, 'persian', 'Persian'),
  (72, 'persian-alola', 'Persian (Alola)'),
  (79, 'arcanine', 'Arcanine'),
  (80, 'arcanine-hisui', 'Arcanine (Hisui)'),
  (86, 'alakazam', 'Alakazam'),
  (87, 'alakazam-mega', 'Alakazam (Mega)'),
  (90, 'machamp', 'Machamp'),
  (93, 'victreebel', 'Victreebel'),
  (1220, 'victreebel-mega', 'Victreebel (Mega)'),
  (108, 'slowbro', 'Slowbro'),
  (109, 'slowbro-mega', 'Slowbro (Mega)'),
  (110, 'slowbro-galar', 'Slowbro (Galar)'),
  (113, 'farfetchd', 'Farfetchd'),
  (127, 'gengar', 'Gengar'),
  (128, 'gengar-mega', 'Gengar (Mega)'),
  (154, 'kangaskhan', 'Kangaskhan'),
  (155, 'kangaskhan-mega', 'Kangaskhan (Mega)'),
  (161, 'starmie', 'Starmie'),
  (1221, 'starmie-mega', 'Starmie (Mega)'),
  (162, 'mr-mime', 'Mr. Mime'),
  (168, 'pinsir', 'Pinsir'),
  (169, 'pinsir-mega', 'Pinsir (Mega)'),
  (170, 'tauros', 'Tauros'),
  (171, 'tauros-paldea-combat', 'Tauros (Paldea-Combat)'),
  (172, 'tauros-paldea-blaze', 'Tauros (Paldea-Blaze)'),
  (173, 'tauros-paldea-aqua', 'Tauros (Paldea-Aqua)'),
  (175, 'gyarados', 'Gyarados'),
  (176, 'gyarados-mega', 'Gyarados (Mega)'),
  (178, 'ditto', 'Ditto'),
  (181, 'vaporeon', 'Vaporeon'),
  (182, 'jolteon', 'Jolteon'),
  (183, 'flareon', 'Flareon'),
  (189, 'aerodactyl', 'Aerodactyl'),
  (190, 'aerodactyl-mega', 'Aerodactyl (Mega)'),
  (191, 'snorlax', 'Snorlax'),
  (200, 'dragonite', 'Dragonite'),
  (1222, 'dragonite-mega', 'Dragonite (Mega)'),
  (207, 'meganium', 'Meganium'),
  (1223, 'meganium-mega', 'Meganium (Mega)'),
  (210, 'typhlosion', 'Typhlosion'),
  (211, 'typhlosion-hisui', 'Typhlosion (Hisui)'),
  (214, 'feraligatr', 'Feraligatr'),
  (1224, 'feraligatr-mega', 'Feraligatr (Mega)'),
  (222, 'ariados', 'Ariados'),
  (235, 'ampharos', 'Ampharos'),
  (236, 'ampharos-mega', 'Ampharos (Mega)'),
  (239, 'azumarill', 'Azumarill'),
  (241, 'politoed', 'Politoed'),
  (252, 'espeon', 'Espeon'),
  (253, 'umbreon', 'Umbreon'),
  (255, 'slowking', 'Slowking'),
  (256, 'slowking-galar', 'Slowking (Galar)'),
  (262, 'forretress', 'Forretress'),
  (265, 'steelix', 'Steelix'),
  (266, 'steelix-mega', 'Steelix (Mega)'),
  (269, 'qwilfish', 'Qwilfish'),
  (271, 'scizor', 'Scizor'),
  (272, 'scizor-mega', 'Scizor (Mega)'),
  (274, 'heracross', 'Heracross'),
  (275, 'heracross-mega', 'Heracross (Mega)'),
  (290, 'skarmory', 'Skarmory'),
  (1225, 'skarmory-mega', 'Skarmory (Mega)'),
  (292, 'houndoom', 'Houndoom'),
  (293, 'houndoom-mega', 'Houndoom (Mega)'),
  (312, 'tyranitar', 'Tyranitar'),
  (313, 'tyranitar-mega', 'Tyranitar (Mega)'),
  (319, 'sceptile', 'Sceptile'),
  (320, 'sceptile-mega', 'Sceptile (Mega)'),
  (323, 'blaziken', 'Blaziken'),
  (324, 'blaziken-mega', 'Blaziken (Mega)'),
  (327, 'swampert', 'Swampert'),
  (328, 'swampert-mega', 'Swampert (Mega)'),
  (349, 'pelipper', 'Pelipper'),
  (352, 'gardevoir', 'Gardevoir'),
  (353, 'gardevoir-mega', 'Gardevoir (Mega)'),
  (373, 'sableye', 'Sableye'),
  (374, 'sableye-mega', 'Sableye (Mega)'),
  (375, 'mawile', 'Mawile'),
  (376, 'mawile-mega', 'Mawile (Mega)'),
  (379, 'aggron', 'Aggron'),
  (380, 'aggron-mega', 'Aggron (Mega)'),
  (382, 'medicham', 'Medicham'),
  (383, 'medicham-mega', 'Medicham (Mega)'),
  (385, 'manectric', 'Manectric'),
  (386, 'manectric-mega', 'Manectric (Mega)'),
  (393, 'swalot', 'Swalot'),
  (395, 'sharpedo', 'Sharpedo'),
  (396, 'sharpedo-mega', 'Sharpedo (Mega)'),
  (400, 'camerupt', 'Camerupt'),
  (401, 'camerupt-mega', 'Camerupt (Mega)'),
  (402, 'torkoal', 'Torkoal'),
  (412, 'altaria', 'Altaria'),
  (413, 'altaria-mega', 'Altaria (Mega)'),
  (429, 'milotic', 'Milotic'),
  (430, 'castform', 'Castform'),
  (436, 'banette', 'Banette'),
  (437, 'banette-mega', 'Banette (Mega)'),
  (441, 'chimecho', 'Chimecho'),
  (1226, 'chimecho-mega', 'Chimecho (Mega)'),
  (442, 'absol', 'Absol'),
  (443, 'absol-mega', 'Absol (Mega)'),
  (1262, 'absol-mega-z', 'Absol (Mega-Z)'),
  (446, 'glalie', 'Glalie'),
  (447, 'glalie-mega', 'Glalie (Mega)'),
  (458, 'salamence', 'Salamence'),
  (459, 'salamence-mega', 'Salamence (Mega)'),
  (462, 'metagross', 'Metagross'),
  (463, 'metagross-mega', 'Metagross (Mega)'),
  (484, 'torterra', 'Torterra'),
  (487, 'infernape', 'Infernape'),
  (490, 'empoleon', 'Empoleon'),
  (493, 'staraptor', 'Staraptor'),
  (1227, 'staraptor-mega', 'Staraptor (Mega)'),
  (500, 'luxray', 'Luxray'),
  (502, 'roserade', 'Roserade'),
  (504, 'rampardos', 'Rampardos'),
  (506, 'bastiodon', 'Bastiodon'),
  (527, 'lopunny', 'Lopunny'),
  (528, 'lopunny-mega', 'Lopunny (Mega)'),
  (542, 'spiritomb', 'Spiritomb'),
  (545, 'garchomp', 'Garchomp'),
  (546, 'garchomp-mega', 'Garchomp (Mega)'),
  (1263, 'garchomp-mega-z', 'Garchomp (Mega-Z)'),
  (549, 'lucario', 'Lucario'),
  (550, 'lucario-mega', 'Lucario (Mega)'),
  (1264, 'lucario-mega-z', 'Lucario (Mega-Z)'),
  (552, 'hippowdon', 'Hippowdon'),
  (556, 'toxicroak', 'Toxicroak'),
  (562, 'abomasnow', 'Abomasnow'),
  (563, 'abomasnow-mega', 'Abomasnow (Mega)'),
  (564, 'weavile', 'Weavile'),
  (567, 'rhyperior', 'Rhyperior'),
  (573, 'leafeon', 'Leafeon'),
  (574, 'glaceon', 'Glaceon'),
  (575, 'gliscor', 'Gliscor'),
  (576, 'mamoswine', 'Mamoswine'),
  (578, 'gallade', 'Gallade'),
  (579, 'gallade-mega', 'Gallade (Mega)'),
  (582, 'froslass', 'Froslass'),
  (1228, 'froslass-mega', 'Froslass (Mega)'),
  (583, 'rotom', 'Rotom'),
  (584, 'rotom-heat', 'Rotom (Heat)'),
  (585, 'rotom-wash', 'Rotom (Wash)'),
  (586, 'rotom-frost', 'Rotom (Frost)'),
  (587, 'rotom-fan', 'Rotom (Fan)'),
  (588, 'rotom-mow', 'Rotom (Mow)'),
  (610, 'serperior', 'Serperior'),
  (613, 'emboar', 'Emboar'),
  (1231, 'emboar-mega', 'Emboar (Mega)'),
  (616, 'samurott', 'Samurott'),
  (617, 'samurott-hisui', 'Samurott (Hisui)'),
  (619, 'watchog', 'Watchog'),
  (624, 'liepard', 'Liepard'),
  (626, 'simisage', 'Simisage'),
  (628, 'simisear', 'Simisear'),
  (630, 'simipour', 'Simipour'),
  (632, 'musharna', 'Musharna'),
  (644, 'excadrill', 'Excadrill'),
  (1232, 'excadrill-mega', 'Excadrill (Mega)'),
  (645, 'audino', 'Audino'),
  (646, 'audino-mega', 'Audino (Mega)'),
  (649, 'conkeldurr', 'Conkeldurr'),
  (660, 'scolipede', 'Scolipede'),
  (1233, 'scolipede-mega', 'Scolipede (Mega)'),
  (662, 'whimsicott', 'Whimsicott'),
  (671, 'krookodile', 'Krookodile'),
  (682, 'scrafty', 'Scrafty'),
  (1234, 'scrafty-mega', 'Scrafty (Mega)'),
  (686, 'cofagrigus', 'Cofagrigus'),
  (692, 'garbodor', 'Garbodor'),
  (695, 'zoroark', 'Zoroark'),
  (696, 'zoroark-hisui', 'Zoroark (Hisui)'),
  (704, 'reuniclus', 'Reuniclus'),
  (709, 'vanilluxe', 'Vanilluxe'),
  (712, 'emolga', 'Emolga'),
  (729, 'eelektross', 'Eelektross'),
  (1235, 'eelektross-mega', 'Eelektross (Mega)'),
  (734, 'chandelure', 'Chandelure'),
  (1236, 'chandelure-mega', 'Chandelure (Mega)'),
  (739, 'beartic', 'Beartic'),
  (743, 'stunfisk', 'Stunfisk'),
  (744, 'stunfisk-galar', 'Stunfisk (Galar)'),
  (749, 'golurk', 'Golurk'),
  (1237, 'golurk-mega', 'Golurk (Mega)'),
  (762, 'hydreigon', 'Hydreigon'),
  (764, 'volcarona', 'Volcarona'),
  (786, 'chesnaught', 'Chesnaught'),
  (1238, 'chesnaught-mega', 'Chesnaught (Mega)'),
  (789, 'delphox', 'Delphox'),
  (1239, 'delphox-mega', 'Delphox (Mega)'),
  (792, 'greninja', 'Greninja'),
  (1240, 'greninja-mega', 'Greninja (Mega)'),
  (795, 'diggersby', 'Diggersby'),
  (798, 'talonflame', 'Talonflame'),
  (801, 'vivillon', 'Vivillon'),
  (803, 'pyroar', 'Pyroar'),
  (1241, 'pyroar-mega', 'Pyroar (Mega)'),
  (1242, 'floette-mega', 'Floette (Mega)'),
  (1261, 'floette-eternal', 'Floette (Eternal)'),
  (806, 'florges', 'Florges'),
  (808, 'gogoat', 'Gogoat'),
  (810, 'pangoro', 'Pangoro'),
  (811, 'furfrou', 'Furfrou'),
  (813, 'meowstic', 'Meowstic'),
  (814, 'meowstic-f', 'Meowstic (F)'),
  (1243, 'meowstic-mega', 'Meowstic (Mega)'),
  (817, 'aegislash', 'Aegislash'),
  (820, 'aromatisse', 'Aromatisse'),
  (822, 'slurpuff', 'Slurpuff'),
  (824, 'malamar', 'Malamar'),
  (1244, 'malamar-mega', 'Malamar (Mega)'),
  (826, 'barbaracle', 'Barbaracle'),
  (1245, 'barbaracle-mega', 'Barbaracle (Mega)'),
  (828, 'dragalge', 'Dragalge'),
  (1246, 'dragalge-mega', 'Dragalge (Mega)'),
  (830, 'clawitzer', 'Clawitzer'),
  (832, 'heliolisk', 'Heliolisk'),
  (834, 'tyrantrum', 'Tyrantrum'),
  (836, 'aurorus', 'Aurorus'),
  (837, 'sylveon', 'Sylveon'),
  (838, 'hawlucha', 'Hawlucha'),
  (1247, 'hawlucha-mega', 'Hawlucha (Mega)'),
  (839, 'dedenne', 'Dedenne'),
  (844, 'goodra', 'Goodra'),
  (845, 'goodra-hisui', 'Goodra (Hisui)'),
  (846, 'klefki', 'Klefki'),
  (848, 'trevenant', 'Trevenant'),
  (853, 'gourgeist', 'Gourgeist'),
  (858, 'avalugg', 'Avalugg'),
  (859, 'avalugg-hisui', 'Avalugg (Hisui)'),
  (861, 'noivern', 'Noivern'),
  (874, 'decidueye', 'Decidueye'),
  (875, 'decidueye-hisui', 'Decidueye (Hisui)'),
  (878, 'incineroar', 'Incineroar'),
  (881, 'primarina', 'Primarina'),
  (884, 'toucannon', 'Toucannon'),
  (891, 'crabominable', 'Crabominable'),
  (1249, 'crabominable-mega', 'Crabominable (Mega)'),
  (900, 'lycanroc', 'Lycanroc'),
  (901, 'lycanroc-midnight', 'Lycanroc (Midnight)'),
  (902, 'lycanroc-dusk', 'Lycanroc (Dusk)'),
  (906, 'toxapex', 'Toxapex'),
  (908, 'mudsdale', 'Mudsdale'),
  (910, 'araquanid', 'Araquanid'),
  (916, 'salazzle', 'Salazzle'),
  (921, 'tsareena', 'Tsareena'),
  (923, 'oranguru', 'Oranguru'),
  (924, 'passimian', 'Passimian'),
  (926, 'golisopod', 'Golisopod'),
  (1250, 'golisopod-mega', 'Golisopod (Mega)'),
  (937, 'mimikyu', 'Mimikyu'),
  (939, 'drampa', 'Drampa'),
  (1251, 'drampa-mega', 'Drampa (Mega)'),
  (943, 'kommo-o', 'Kommo-o'),
  (974, 'rillaboom', 'Rillaboom'),
  (977, 'cinderace', 'Cinderace'),
  (980, 'inteleon', 'Inteleon'),
  (985, 'corviknight', 'Corviknight'),
  (990, 'thievul', 'Thievul'),
  (1003, 'flapple', 'Flapple'),
  (1004, 'appletun', 'Appletun'),
  (1006, 'sandaconda', 'Sandaconda'),
  (1011, 'toxtricity', 'Toxtricity'),
  (1012, 'toxtricity-low-key', 'Toxtricity (Low-Key)'),
  (1016, 'grapploct', 'Grapploct'),
  (1018, 'polteageist', 'Polteageist'),
  (1021, 'hatterene', 'Hatterene'),
  (1024, 'grimmsnarl', 'Grimmsnarl'),
  (1026, 'perrserker', 'Perrserker'),
  (1028, 'sirfetchd', 'Sirfetchd'),
  (1029, 'mr-rime', 'Mr. Rime'),
  (1032, 'alcremie', 'Alcremie'),
  (1033, 'falinks', 'Falinks'),
  (1254, 'falinks-mega', 'Falinks (Mega)'),
  (1034, 'pincurchin', 'Pincurchin'),
  (1040, 'indeedee', 'Indeedee'),
  (1041, 'indeedee-f', 'Indeedee (F)'),
  (1042, 'morpeko', 'Morpeko'),
  (1053, 'dragapult', 'Dragapult'),
  (1071, 'wyrdeer', 'Wyrdeer'),
  (1072, 'kleavor', 'Kleavor'),
  (1074, 'basculegion', 'Basculegion'),
  (1075, 'basculegion-f', 'Basculegion (F)'),
  (1076, 'sneasler', 'Sneasler'),
  (1077, 'overqwil', 'Overqwil'),
  (1082, 'meowscarada', 'Meowscarada'),
  (1085, 'skeledirge', 'Skeledirge'),
  (1088, 'quaquaval', 'Quaquaval'),
  (1098, 'pawmot', 'Pawmot'),
  (1100, 'maushold', 'Maushold'),
  (1106, 'arboliva', 'Arboliva'),
  (1107, 'squawkabilly', 'Squawkabilly'),
  (1113, 'garganacl', 'Garganacl'),
  (1115, 'armarouge', 'Armarouge'),
  (1116, 'ceruledge', 'Ceruledge'),
  (1118, 'bellibolt', 'Bellibolt'),
  (1122, 'mabosstiff', 'Mabosstiff'),
  (1131, 'scovillain', 'Scovillain'),
  (1255, 'scovillain-mega', 'Scovillain (Mega)'),
  (1135, 'espathra', 'Espathra'),
  (1138, 'tinkaton', 'Tinkaton'),
  (1143, 'palafin', 'Palafin'),
  (1148, 'orthworm', 'Orthworm'),
  (1150, 'glimmora', 'Glimmora'),
  (1256, 'glimmora-mega', 'Glimmora (Mega)'),
  (1152, 'houndstone', 'Houndstone'),
  (1159, 'annihilape', 'Annihilape'),
  (1161, 'farigiraf', 'Farigiraf'),
  (1164, 'kingambit', 'Kingambit'),
  (1179, 'baxcalibur', 'Baxcalibur'),
  (1260, 'baxcalibur-mega', 'Baxcalibur (Mega)'),
  (1182, 'gholdengo', 'Gholdengo'),
  (1198, 'sinistcha', 'Sinistcha'),
  (1206, 'archaludon', 'Archaludon'),
  (1207, 'hydrapple', 'Hydrapple');
