-- Pokémon types, from Showdown's pokedex (play.pokemonshowdown.com/data/pokedex.json).
-- Space-separated, primary type first. Sprites live in static/sprites/<slug>.png.
ALTER TABLE pokemon ADD COLUMN types TEXT NOT NULL DEFAULT '';

UPDATE pokemon SET types = 'Grass Poison' WHERE slug = 'venusaur';
UPDATE pokemon SET types = 'Grass Poison' WHERE slug = 'venusaur-mega';
UPDATE pokemon SET types = 'Fire Flying' WHERE slug = 'charizard';
UPDATE pokemon SET types = 'Fire Dragon' WHERE slug = 'charizard-mega-x';
UPDATE pokemon SET types = 'Fire Flying' WHERE slug = 'charizard-mega-y';
UPDATE pokemon SET types = 'Water' WHERE slug = 'blastoise';
UPDATE pokemon SET types = 'Water' WHERE slug = 'blastoise-mega';
UPDATE pokemon SET types = 'Bug Poison' WHERE slug = 'beedrill';
UPDATE pokemon SET types = 'Bug Poison' WHERE slug = 'beedrill-mega';
UPDATE pokemon SET types = 'Normal Flying' WHERE slug = 'pidgeot';
UPDATE pokemon SET types = 'Normal Flying' WHERE slug = 'pidgeot-mega';
UPDATE pokemon SET types = 'Poison' WHERE slug = 'arbok';
UPDATE pokemon SET types = 'Electric' WHERE slug = 'pikachu';
UPDATE pokemon SET types = 'Electric' WHERE slug = 'raichu';
UPDATE pokemon SET types = 'Electric Psychic' WHERE slug = 'raichu-alola';
UPDATE pokemon SET types = 'Electric' WHERE slug = 'raichu-mega-x';
UPDATE pokemon SET types = 'Electric' WHERE slug = 'raichu-mega-y';
UPDATE pokemon SET types = 'Fairy' WHERE slug = 'clefable';
UPDATE pokemon SET types = 'Fairy Flying' WHERE slug = 'clefable-mega';
UPDATE pokemon SET types = 'Fire' WHERE slug = 'ninetales';
UPDATE pokemon SET types = 'Ice Fairy' WHERE slug = 'ninetales-alola';
UPDATE pokemon SET types = 'Normal Fairy' WHERE slug = 'wigglytuff';
UPDATE pokemon SET types = 'Grass Poison' WHERE slug = 'vileplume';
UPDATE pokemon SET types = 'Normal' WHERE slug = 'persian';
UPDATE pokemon SET types = 'Dark' WHERE slug = 'persian-alola';
UPDATE pokemon SET types = 'Fire' WHERE slug = 'arcanine';
UPDATE pokemon SET types = 'Fire Rock' WHERE slug = 'arcanine-hisui';
UPDATE pokemon SET types = 'Psychic' WHERE slug = 'alakazam';
UPDATE pokemon SET types = 'Psychic' WHERE slug = 'alakazam-mega';
UPDATE pokemon SET types = 'Fighting' WHERE slug = 'machamp';
UPDATE pokemon SET types = 'Grass Poison' WHERE slug = 'victreebel';
UPDATE pokemon SET types = 'Grass Poison' WHERE slug = 'victreebel-mega';
UPDATE pokemon SET types = 'Water Psychic' WHERE slug = 'slowbro';
UPDATE pokemon SET types = 'Water Psychic' WHERE slug = 'slowbro-mega';
UPDATE pokemon SET types = 'Poison Psychic' WHERE slug = 'slowbro-galar';
UPDATE pokemon SET types = 'Normal Flying' WHERE slug = 'farfetchd';
UPDATE pokemon SET types = 'Ghost Poison' WHERE slug = 'gengar';
UPDATE pokemon SET types = 'Ghost Poison' WHERE slug = 'gengar-mega';
UPDATE pokemon SET types = 'Normal' WHERE slug = 'kangaskhan';
UPDATE pokemon SET types = 'Normal' WHERE slug = 'kangaskhan-mega';
UPDATE pokemon SET types = 'Water Psychic' WHERE slug = 'starmie';
UPDATE pokemon SET types = 'Water Psychic' WHERE slug = 'starmie-mega';
UPDATE pokemon SET types = 'Psychic Fairy' WHERE slug = 'mr-mime';
UPDATE pokemon SET types = 'Bug' WHERE slug = 'pinsir';
UPDATE pokemon SET types = 'Bug Flying' WHERE slug = 'pinsir-mega';
UPDATE pokemon SET types = 'Normal' WHERE slug = 'tauros';
UPDATE pokemon SET types = 'Fighting' WHERE slug = 'tauros-paldea-combat';
UPDATE pokemon SET types = 'Fighting Fire' WHERE slug = 'tauros-paldea-blaze';
UPDATE pokemon SET types = 'Fighting Water' WHERE slug = 'tauros-paldea-aqua';
UPDATE pokemon SET types = 'Water Flying' WHERE slug = 'gyarados';
UPDATE pokemon SET types = 'Water Dark' WHERE slug = 'gyarados-mega';
UPDATE pokemon SET types = 'Normal' WHERE slug = 'ditto';
UPDATE pokemon SET types = 'Water' WHERE slug = 'vaporeon';
UPDATE pokemon SET types = 'Electric' WHERE slug = 'jolteon';
UPDATE pokemon SET types = 'Fire' WHERE slug = 'flareon';
UPDATE pokemon SET types = 'Rock Flying' WHERE slug = 'aerodactyl';
UPDATE pokemon SET types = 'Rock Flying' WHERE slug = 'aerodactyl-mega';
UPDATE pokemon SET types = 'Normal' WHERE slug = 'snorlax';
UPDATE pokemon SET types = 'Dragon Flying' WHERE slug = 'dragonite';
UPDATE pokemon SET types = 'Dragon Flying' WHERE slug = 'dragonite-mega';
UPDATE pokemon SET types = 'Grass' WHERE slug = 'meganium';
UPDATE pokemon SET types = 'Grass Fairy' WHERE slug = 'meganium-mega';
UPDATE pokemon SET types = 'Fire' WHERE slug = 'typhlosion';
UPDATE pokemon SET types = 'Fire Ghost' WHERE slug = 'typhlosion-hisui';
UPDATE pokemon SET types = 'Water' WHERE slug = 'feraligatr';
UPDATE pokemon SET types = 'Water Dragon' WHERE slug = 'feraligatr-mega';
UPDATE pokemon SET types = 'Bug Poison' WHERE slug = 'ariados';
UPDATE pokemon SET types = 'Electric' WHERE slug = 'ampharos';
UPDATE pokemon SET types = 'Electric Dragon' WHERE slug = 'ampharos-mega';
UPDATE pokemon SET types = 'Water Fairy' WHERE slug = 'azumarill';
UPDATE pokemon SET types = 'Water' WHERE slug = 'politoed';
UPDATE pokemon SET types = 'Psychic' WHERE slug = 'espeon';
UPDATE pokemon SET types = 'Dark' WHERE slug = 'umbreon';
UPDATE pokemon SET types = 'Water Psychic' WHERE slug = 'slowking';
UPDATE pokemon SET types = 'Poison Psychic' WHERE slug = 'slowking-galar';
UPDATE pokemon SET types = 'Bug Steel' WHERE slug = 'forretress';
UPDATE pokemon SET types = 'Steel Ground' WHERE slug = 'steelix';
UPDATE pokemon SET types = 'Steel Ground' WHERE slug = 'steelix-mega';
UPDATE pokemon SET types = 'Water Poison' WHERE slug = 'qwilfish';
UPDATE pokemon SET types = 'Bug Steel' WHERE slug = 'scizor';
UPDATE pokemon SET types = 'Bug Steel' WHERE slug = 'scizor-mega';
UPDATE pokemon SET types = 'Bug Fighting' WHERE slug = 'heracross';
UPDATE pokemon SET types = 'Bug Fighting' WHERE slug = 'heracross-mega';
UPDATE pokemon SET types = 'Steel Flying' WHERE slug = 'skarmory';
UPDATE pokemon SET types = 'Steel Flying' WHERE slug = 'skarmory-mega';
UPDATE pokemon SET types = 'Dark Fire' WHERE slug = 'houndoom';
UPDATE pokemon SET types = 'Dark Fire' WHERE slug = 'houndoom-mega';
UPDATE pokemon SET types = 'Rock Dark' WHERE slug = 'tyranitar';
UPDATE pokemon SET types = 'Rock Dark' WHERE slug = 'tyranitar-mega';
UPDATE pokemon SET types = 'Grass' WHERE slug = 'sceptile';
UPDATE pokemon SET types = 'Grass Dragon' WHERE slug = 'sceptile-mega';
UPDATE pokemon SET types = 'Fire Fighting' WHERE slug = 'blaziken';
UPDATE pokemon SET types = 'Fire Fighting' WHERE slug = 'blaziken-mega';
UPDATE pokemon SET types = 'Water Ground' WHERE slug = 'swampert';
UPDATE pokemon SET types = 'Water Ground' WHERE slug = 'swampert-mega';
UPDATE pokemon SET types = 'Water Flying' WHERE slug = 'pelipper';
UPDATE pokemon SET types = 'Psychic Fairy' WHERE slug = 'gardevoir';
UPDATE pokemon SET types = 'Psychic Fairy' WHERE slug = 'gardevoir-mega';
UPDATE pokemon SET types = 'Dark Ghost' WHERE slug = 'sableye';
UPDATE pokemon SET types = 'Dark Ghost' WHERE slug = 'sableye-mega';
UPDATE pokemon SET types = 'Steel Fairy' WHERE slug = 'mawile';
UPDATE pokemon SET types = 'Steel Fairy' WHERE slug = 'mawile-mega';
UPDATE pokemon SET types = 'Steel Rock' WHERE slug = 'aggron';
UPDATE pokemon SET types = 'Steel' WHERE slug = 'aggron-mega';
UPDATE pokemon SET types = 'Fighting Psychic' WHERE slug = 'medicham';
UPDATE pokemon SET types = 'Fighting Psychic' WHERE slug = 'medicham-mega';
UPDATE pokemon SET types = 'Electric' WHERE slug = 'manectric';
UPDATE pokemon SET types = 'Electric' WHERE slug = 'manectric-mega';
UPDATE pokemon SET types = 'Poison' WHERE slug = 'swalot';
UPDATE pokemon SET types = 'Water Dark' WHERE slug = 'sharpedo';
UPDATE pokemon SET types = 'Water Dark' WHERE slug = 'sharpedo-mega';
UPDATE pokemon SET types = 'Fire Ground' WHERE slug = 'camerupt';
UPDATE pokemon SET types = 'Fire Ground' WHERE slug = 'camerupt-mega';
UPDATE pokemon SET types = 'Fire' WHERE slug = 'torkoal';
UPDATE pokemon SET types = 'Dragon Flying' WHERE slug = 'altaria';
UPDATE pokemon SET types = 'Dragon Fairy' WHERE slug = 'altaria-mega';
UPDATE pokemon SET types = 'Water' WHERE slug = 'milotic';
UPDATE pokemon SET types = 'Normal' WHERE slug = 'castform';
UPDATE pokemon SET types = 'Ghost' WHERE slug = 'banette';
UPDATE pokemon SET types = 'Ghost' WHERE slug = 'banette-mega';
UPDATE pokemon SET types = 'Psychic' WHERE slug = 'chimecho';
UPDATE pokemon SET types = 'Psychic Steel' WHERE slug = 'chimecho-mega';
UPDATE pokemon SET types = 'Dark' WHERE slug = 'absol';
UPDATE pokemon SET types = 'Dark' WHERE slug = 'absol-mega';
UPDATE pokemon SET types = 'Dark Ghost' WHERE slug = 'absol-mega-z';
UPDATE pokemon SET types = 'Ice' WHERE slug = 'glalie';
UPDATE pokemon SET types = 'Ice' WHERE slug = 'glalie-mega';
UPDATE pokemon SET types = 'Dragon Flying' WHERE slug = 'salamence';
UPDATE pokemon SET types = 'Dragon Flying' WHERE slug = 'salamence-mega';
UPDATE pokemon SET types = 'Steel Psychic' WHERE slug = 'metagross';
UPDATE pokemon SET types = 'Steel Psychic' WHERE slug = 'metagross-mega';
UPDATE pokemon SET types = 'Grass Ground' WHERE slug = 'torterra';
UPDATE pokemon SET types = 'Fire Fighting' WHERE slug = 'infernape';
UPDATE pokemon SET types = 'Water Steel' WHERE slug = 'empoleon';
UPDATE pokemon SET types = 'Normal Flying' WHERE slug = 'staraptor';
UPDATE pokemon SET types = 'Fighting Flying' WHERE slug = 'staraptor-mega';
UPDATE pokemon SET types = 'Electric' WHERE slug = 'luxray';
UPDATE pokemon SET types = 'Grass Poison' WHERE slug = 'roserade';
UPDATE pokemon SET types = 'Rock' WHERE slug = 'rampardos';
UPDATE pokemon SET types = 'Rock Steel' WHERE slug = 'bastiodon';
UPDATE pokemon SET types = 'Normal' WHERE slug = 'lopunny';
UPDATE pokemon SET types = 'Normal Fighting' WHERE slug = 'lopunny-mega';
UPDATE pokemon SET types = 'Ghost Dark' WHERE slug = 'spiritomb';
UPDATE pokemon SET types = 'Dragon Ground' WHERE slug = 'garchomp';
UPDATE pokemon SET types = 'Dragon Ground' WHERE slug = 'garchomp-mega';
UPDATE pokemon SET types = 'Dragon' WHERE slug = 'garchomp-mega-z';
UPDATE pokemon SET types = 'Fighting Steel' WHERE slug = 'lucario';
UPDATE pokemon SET types = 'Fighting Steel' WHERE slug = 'lucario-mega';
UPDATE pokemon SET types = 'Fighting Steel' WHERE slug = 'lucario-mega-z';
UPDATE pokemon SET types = 'Ground' WHERE slug = 'hippowdon';
UPDATE pokemon SET types = 'Poison Fighting' WHERE slug = 'toxicroak';
UPDATE pokemon SET types = 'Grass Ice' WHERE slug = 'abomasnow';
UPDATE pokemon SET types = 'Grass Ice' WHERE slug = 'abomasnow-mega';
UPDATE pokemon SET types = 'Dark Ice' WHERE slug = 'weavile';
UPDATE pokemon SET types = 'Ground Rock' WHERE slug = 'rhyperior';
UPDATE pokemon SET types = 'Grass' WHERE slug = 'leafeon';
UPDATE pokemon SET types = 'Ice' WHERE slug = 'glaceon';
UPDATE pokemon SET types = 'Ground Flying' WHERE slug = 'gliscor';
UPDATE pokemon SET types = 'Ice Ground' WHERE slug = 'mamoswine';
UPDATE pokemon SET types = 'Psychic Fighting' WHERE slug = 'gallade';
UPDATE pokemon SET types = 'Psychic Fighting' WHERE slug = 'gallade-mega';
UPDATE pokemon SET types = 'Ice Ghost' WHERE slug = 'froslass';
UPDATE pokemon SET types = 'Ice Ghost' WHERE slug = 'froslass-mega';
UPDATE pokemon SET types = 'Electric Ghost' WHERE slug = 'rotom';
UPDATE pokemon SET types = 'Electric Fire' WHERE slug = 'rotom-heat';
UPDATE pokemon SET types = 'Electric Water' WHERE slug = 'rotom-wash';
UPDATE pokemon SET types = 'Electric Ice' WHERE slug = 'rotom-frost';
UPDATE pokemon SET types = 'Electric Flying' WHERE slug = 'rotom-fan';
UPDATE pokemon SET types = 'Electric Grass' WHERE slug = 'rotom-mow';
UPDATE pokemon SET types = 'Grass' WHERE slug = 'serperior';
UPDATE pokemon SET types = 'Fire Fighting' WHERE slug = 'emboar';
UPDATE pokemon SET types = 'Fire Fighting' WHERE slug = 'emboar-mega';
UPDATE pokemon SET types = 'Water' WHERE slug = 'samurott';
UPDATE pokemon SET types = 'Water Dark' WHERE slug = 'samurott-hisui';
UPDATE pokemon SET types = 'Normal' WHERE slug = 'watchog';
UPDATE pokemon SET types = 'Dark' WHERE slug = 'liepard';
UPDATE pokemon SET types = 'Grass' WHERE slug = 'simisage';
UPDATE pokemon SET types = 'Fire' WHERE slug = 'simisear';
UPDATE pokemon SET types = 'Water' WHERE slug = 'simipour';
UPDATE pokemon SET types = 'Psychic' WHERE slug = 'musharna';
UPDATE pokemon SET types = 'Ground Steel' WHERE slug = 'excadrill';
UPDATE pokemon SET types = 'Ground Steel' WHERE slug = 'excadrill-mega';
UPDATE pokemon SET types = 'Normal' WHERE slug = 'audino';
UPDATE pokemon SET types = 'Normal Fairy' WHERE slug = 'audino-mega';
UPDATE pokemon SET types = 'Fighting' WHERE slug = 'conkeldurr';
UPDATE pokemon SET types = 'Bug Poison' WHERE slug = 'scolipede';
UPDATE pokemon SET types = 'Bug Poison' WHERE slug = 'scolipede-mega';
UPDATE pokemon SET types = 'Grass Fairy' WHERE slug = 'whimsicott';
UPDATE pokemon SET types = 'Ground Dark' WHERE slug = 'krookodile';
UPDATE pokemon SET types = 'Dark Fighting' WHERE slug = 'scrafty';
UPDATE pokemon SET types = 'Dark Fighting' WHERE slug = 'scrafty-mega';
UPDATE pokemon SET types = 'Ghost' WHERE slug = 'cofagrigus';
UPDATE pokemon SET types = 'Poison' WHERE slug = 'garbodor';
UPDATE pokemon SET types = 'Dark' WHERE slug = 'zoroark';
UPDATE pokemon SET types = 'Normal Ghost' WHERE slug = 'zoroark-hisui';
UPDATE pokemon SET types = 'Psychic' WHERE slug = 'reuniclus';
UPDATE pokemon SET types = 'Ice' WHERE slug = 'vanilluxe';
UPDATE pokemon SET types = 'Electric Flying' WHERE slug = 'emolga';
UPDATE pokemon SET types = 'Electric' WHERE slug = 'eelektross';
UPDATE pokemon SET types = 'Electric' WHERE slug = 'eelektross-mega';
UPDATE pokemon SET types = 'Ghost Fire' WHERE slug = 'chandelure';
UPDATE pokemon SET types = 'Ghost Fire' WHERE slug = 'chandelure-mega';
UPDATE pokemon SET types = 'Ice' WHERE slug = 'beartic';
UPDATE pokemon SET types = 'Ground Electric' WHERE slug = 'stunfisk';
UPDATE pokemon SET types = 'Ground Steel' WHERE slug = 'stunfisk-galar';
UPDATE pokemon SET types = 'Ground Ghost' WHERE slug = 'golurk';
UPDATE pokemon SET types = 'Ground Ghost' WHERE slug = 'golurk-mega';
UPDATE pokemon SET types = 'Dark Dragon' WHERE slug = 'hydreigon';
UPDATE pokemon SET types = 'Bug Fire' WHERE slug = 'volcarona';
UPDATE pokemon SET types = 'Grass Fighting' WHERE slug = 'chesnaught';
UPDATE pokemon SET types = 'Grass Fighting' WHERE slug = 'chesnaught-mega';
UPDATE pokemon SET types = 'Fire Psychic' WHERE slug = 'delphox';
UPDATE pokemon SET types = 'Fire Psychic' WHERE slug = 'delphox-mega';
UPDATE pokemon SET types = 'Water Dark' WHERE slug = 'greninja';
UPDATE pokemon SET types = 'Water Dark' WHERE slug = 'greninja-mega';
UPDATE pokemon SET types = 'Normal Ground' WHERE slug = 'diggersby';
UPDATE pokemon SET types = 'Fire Flying' WHERE slug = 'talonflame';
UPDATE pokemon SET types = 'Bug Flying' WHERE slug = 'vivillon';
UPDATE pokemon SET types = 'Fire Normal' WHERE slug = 'pyroar';
UPDATE pokemon SET types = 'Fire Normal' WHERE slug = 'pyroar-mega';
UPDATE pokemon SET types = 'Fairy' WHERE slug = 'floette-mega';
UPDATE pokemon SET types = 'Fairy' WHERE slug = 'floette-eternal';
UPDATE pokemon SET types = 'Fairy' WHERE slug = 'florges';
UPDATE pokemon SET types = 'Grass' WHERE slug = 'gogoat';
UPDATE pokemon SET types = 'Fighting Dark' WHERE slug = 'pangoro';
UPDATE pokemon SET types = 'Normal' WHERE slug = 'furfrou';
UPDATE pokemon SET types = 'Psychic' WHERE slug = 'meowstic';
UPDATE pokemon SET types = 'Psychic' WHERE slug = 'meowstic-f';
UPDATE pokemon SET types = 'Psychic' WHERE slug = 'meowstic-mega';
UPDATE pokemon SET types = 'Steel Ghost' WHERE slug = 'aegislash';
UPDATE pokemon SET types = 'Fairy' WHERE slug = 'aromatisse';
UPDATE pokemon SET types = 'Fairy' WHERE slug = 'slurpuff';
UPDATE pokemon SET types = 'Dark Psychic' WHERE slug = 'malamar';
UPDATE pokemon SET types = 'Dark Psychic' WHERE slug = 'malamar-mega';
UPDATE pokemon SET types = 'Rock Water' WHERE slug = 'barbaracle';
UPDATE pokemon SET types = 'Rock Fighting' WHERE slug = 'barbaracle-mega';
UPDATE pokemon SET types = 'Poison Dragon' WHERE slug = 'dragalge';
UPDATE pokemon SET types = 'Poison Dragon' WHERE slug = 'dragalge-mega';
UPDATE pokemon SET types = 'Water' WHERE slug = 'clawitzer';
UPDATE pokemon SET types = 'Electric Normal' WHERE slug = 'heliolisk';
UPDATE pokemon SET types = 'Rock Dragon' WHERE slug = 'tyrantrum';
UPDATE pokemon SET types = 'Rock Ice' WHERE slug = 'aurorus';
UPDATE pokemon SET types = 'Fairy' WHERE slug = 'sylveon';
UPDATE pokemon SET types = 'Fighting Flying' WHERE slug = 'hawlucha';
UPDATE pokemon SET types = 'Fighting Flying' WHERE slug = 'hawlucha-mega';
UPDATE pokemon SET types = 'Electric Fairy' WHERE slug = 'dedenne';
UPDATE pokemon SET types = 'Dragon' WHERE slug = 'goodra';
UPDATE pokemon SET types = 'Steel Dragon' WHERE slug = 'goodra-hisui';
UPDATE pokemon SET types = 'Steel Fairy' WHERE slug = 'klefki';
UPDATE pokemon SET types = 'Ghost Grass' WHERE slug = 'trevenant';
UPDATE pokemon SET types = 'Ghost Grass' WHERE slug = 'gourgeist';
UPDATE pokemon SET types = 'Ice' WHERE slug = 'avalugg';
UPDATE pokemon SET types = 'Ice Rock' WHERE slug = 'avalugg-hisui';
UPDATE pokemon SET types = 'Flying Dragon' WHERE slug = 'noivern';
UPDATE pokemon SET types = 'Grass Ghost' WHERE slug = 'decidueye';
UPDATE pokemon SET types = 'Grass Fighting' WHERE slug = 'decidueye-hisui';
UPDATE pokemon SET types = 'Fire Dark' WHERE slug = 'incineroar';
UPDATE pokemon SET types = 'Water Fairy' WHERE slug = 'primarina';
UPDATE pokemon SET types = 'Normal Flying' WHERE slug = 'toucannon';
UPDATE pokemon SET types = 'Fighting Ice' WHERE slug = 'crabominable';
UPDATE pokemon SET types = 'Fighting Ice' WHERE slug = 'crabominable-mega';
UPDATE pokemon SET types = 'Rock' WHERE slug = 'lycanroc';
UPDATE pokemon SET types = 'Rock' WHERE slug = 'lycanroc-midnight';
UPDATE pokemon SET types = 'Rock' WHERE slug = 'lycanroc-dusk';
UPDATE pokemon SET types = 'Poison Water' WHERE slug = 'toxapex';
UPDATE pokemon SET types = 'Ground' WHERE slug = 'mudsdale';
UPDATE pokemon SET types = 'Water Bug' WHERE slug = 'araquanid';
UPDATE pokemon SET types = 'Poison Fire' WHERE slug = 'salazzle';
UPDATE pokemon SET types = 'Grass' WHERE slug = 'tsareena';
UPDATE pokemon SET types = 'Normal Psychic' WHERE slug = 'oranguru';
UPDATE pokemon SET types = 'Fighting' WHERE slug = 'passimian';
UPDATE pokemon SET types = 'Bug Water' WHERE slug = 'golisopod';
UPDATE pokemon SET types = 'Bug Steel' WHERE slug = 'golisopod-mega';
UPDATE pokemon SET types = 'Ghost Fairy' WHERE slug = 'mimikyu';
UPDATE pokemon SET types = 'Normal Dragon' WHERE slug = 'drampa';
UPDATE pokemon SET types = 'Normal Dragon' WHERE slug = 'drampa-mega';
UPDATE pokemon SET types = 'Dragon Fighting' WHERE slug = 'kommo-o';
UPDATE pokemon SET types = 'Grass' WHERE slug = 'rillaboom';
UPDATE pokemon SET types = 'Fire' WHERE slug = 'cinderace';
UPDATE pokemon SET types = 'Water' WHERE slug = 'inteleon';
UPDATE pokemon SET types = 'Flying Steel' WHERE slug = 'corviknight';
UPDATE pokemon SET types = 'Dark' WHERE slug = 'thievul';
UPDATE pokemon SET types = 'Grass Dragon' WHERE slug = 'flapple';
UPDATE pokemon SET types = 'Grass Dragon' WHERE slug = 'appletun';
UPDATE pokemon SET types = 'Ground' WHERE slug = 'sandaconda';
UPDATE pokemon SET types = 'Electric Poison' WHERE slug = 'toxtricity';
UPDATE pokemon SET types = 'Electric Poison' WHERE slug = 'toxtricity-low-key';
UPDATE pokemon SET types = 'Fighting' WHERE slug = 'grapploct';
UPDATE pokemon SET types = 'Ghost' WHERE slug = 'polteageist';
UPDATE pokemon SET types = 'Psychic Fairy' WHERE slug = 'hatterene';
UPDATE pokemon SET types = 'Dark Fairy' WHERE slug = 'grimmsnarl';
UPDATE pokemon SET types = 'Steel' WHERE slug = 'perrserker';
UPDATE pokemon SET types = 'Fighting' WHERE slug = 'sirfetchd';
UPDATE pokemon SET types = 'Ice Psychic' WHERE slug = 'mr-rime';
UPDATE pokemon SET types = 'Fairy' WHERE slug = 'alcremie';
UPDATE pokemon SET types = 'Fighting' WHERE slug = 'falinks';
UPDATE pokemon SET types = 'Fighting' WHERE slug = 'falinks-mega';
UPDATE pokemon SET types = 'Electric' WHERE slug = 'pincurchin';
UPDATE pokemon SET types = 'Psychic Normal' WHERE slug = 'indeedee';
UPDATE pokemon SET types = 'Psychic Normal' WHERE slug = 'indeedee-f';
UPDATE pokemon SET types = 'Electric Dark' WHERE slug = 'morpeko';
UPDATE pokemon SET types = 'Dragon Ghost' WHERE slug = 'dragapult';
UPDATE pokemon SET types = 'Normal Psychic' WHERE slug = 'wyrdeer';
UPDATE pokemon SET types = 'Bug Rock' WHERE slug = 'kleavor';
UPDATE pokemon SET types = 'Water Ghost' WHERE slug = 'basculegion';
UPDATE pokemon SET types = 'Water Ghost' WHERE slug = 'basculegion-f';
UPDATE pokemon SET types = 'Fighting Poison' WHERE slug = 'sneasler';
UPDATE pokemon SET types = 'Dark Poison' WHERE slug = 'overqwil';
UPDATE pokemon SET types = 'Grass Dark' WHERE slug = 'meowscarada';
UPDATE pokemon SET types = 'Fire Ghost' WHERE slug = 'skeledirge';
UPDATE pokemon SET types = 'Water Fighting' WHERE slug = 'quaquaval';
UPDATE pokemon SET types = 'Electric Fighting' WHERE slug = 'pawmot';
UPDATE pokemon SET types = 'Normal' WHERE slug = 'maushold';
UPDATE pokemon SET types = 'Grass Normal' WHERE slug = 'arboliva';
UPDATE pokemon SET types = 'Normal Flying' WHERE slug = 'squawkabilly';
UPDATE pokemon SET types = 'Rock' WHERE slug = 'garganacl';
UPDATE pokemon SET types = 'Fire Psychic' WHERE slug = 'armarouge';
UPDATE pokemon SET types = 'Fire Ghost' WHERE slug = 'ceruledge';
UPDATE pokemon SET types = 'Electric' WHERE slug = 'bellibolt';
UPDATE pokemon SET types = 'Dark' WHERE slug = 'mabosstiff';
UPDATE pokemon SET types = 'Grass Fire' WHERE slug = 'scovillain';
UPDATE pokemon SET types = 'Grass Fire' WHERE slug = 'scovillain-mega';
UPDATE pokemon SET types = 'Psychic' WHERE slug = 'espathra';
UPDATE pokemon SET types = 'Fairy Steel' WHERE slug = 'tinkaton';
UPDATE pokemon SET types = 'Water' WHERE slug = 'palafin';
UPDATE pokemon SET types = 'Steel' WHERE slug = 'orthworm';
UPDATE pokemon SET types = 'Rock Poison' WHERE slug = 'glimmora';
UPDATE pokemon SET types = 'Rock Poison' WHERE slug = 'glimmora-mega';
UPDATE pokemon SET types = 'Ghost' WHERE slug = 'houndstone';
UPDATE pokemon SET types = 'Fighting Ghost' WHERE slug = 'annihilape';
UPDATE pokemon SET types = 'Normal Psychic' WHERE slug = 'farigiraf';
UPDATE pokemon SET types = 'Dark Steel' WHERE slug = 'kingambit';
UPDATE pokemon SET types = 'Dragon Ice' WHERE slug = 'baxcalibur';
UPDATE pokemon SET types = 'Dragon Ice' WHERE slug = 'baxcalibur-mega';
UPDATE pokemon SET types = 'Steel Ghost' WHERE slug = 'gholdengo';
UPDATE pokemon SET types = 'Grass Ghost' WHERE slug = 'sinistcha';
UPDATE pokemon SET types = 'Steel Dragon' WHERE slug = 'archaludon';
UPDATE pokemon SET types = 'Grass Dragon' WHERE slug = 'hydrapple';
